### PR TITLE
Article/User

### PR DESCRIPTION
**Pull request by MikaKC**
Ok

### CODE REVIEW

**Comment by MoldyMacaroniX** [comment]
I think it'd be a good idea to add some images of what is being discussed in the article (i.e. rather than have links to an image, embed the image in the site). If someone could do that then I'll merge this!

**Comment by MikaKC** [comment]
> I think it'd be a good idea to add some images of what is being discussed in the article (i.e. rather than have links to an image, embed the image in the site). If someone could do that then I'll merge this!

i think so to wait a min

**Comment by MoldyMacaroniX** [comment]
Please keep images on a separate line, with blank lines above and below it. They are not to be used inline.

I recommend keeping the links but adding the respective image below its respective paragraph.

Also, the images are not correct. Use links that work and test in a dev environment.

**Comment by MoldyMacaroniX** [comment]
Also, treat video embeds like images - they too should not be inline

**Comment by MoldyMacaroniX** [comment]
@MikaKC see what I wrote in [#28](https://github.com/MoldyMacaroniX/gd-website/pull/54/commits/28b141f2a02d8839fa78c213dc957c64343b903f).

**Pull request merged**
